version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ${ENV_DB_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - ${ENV_PORT}:80
    links:
      - db
    volumes:
      - ${ENV_NEXTCLOUD_DIR}:/var/www/html
    restart: always
